import {
  Activity,
  BadgeCheck,
  BarChart3,
  Bell,
  Building2,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CircleDollarSign,
  CirclePlus,
  Clock3,
  ClipboardCheck,
  ClipboardList,
  ClipboardPlus,
  Files,
  FilePlus2,
  FileText,
  Flag,
  Fuel,
  Gauge,
  KanbanSquare,
  Keyboard,
  LayoutDashboard,
  ListChecks,
  MessageCircle,
  PackagePlus,
  PackageSearch,
  PanelTop,
  ReceiptText,
  Repeat2,
  Route,
  Satellite,
  Send,
  ShieldCheck,
  ShoppingCart,
  Tags,
  TrendingUp,
  Truck,
  TriangleAlert,
  Users,
  Warehouse,
  Wrench,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

export const sidebarIconMap: Record<string, LucideIcon> = {
  activity: Activity,
  'badge-check': BadgeCheck,
  'bar-chart-3': BarChart3,
  bell: Bell,
  'building-2': Building2,
  'calendar-check': CalendarCheck,
  'calendar-clock': CalendarClock,
  'calendar-days': CalendarDays,
  'circle-dollar-sign': CircleDollarSign,
  'circle-plus': CirclePlus,
  'clock-3': Clock3,
  'clipboard-check': ClipboardCheck,
  'clipboard-list': ClipboardList,
  'clipboard-plus': ClipboardPlus,
  files: Files,
  'file-plus-2': FilePlus2,
  'file-text': FileText,
  flag: Flag,
  fuel: Fuel,
  gauge: Gauge,
  'kanban-square': KanbanSquare,
  keyboard: Keyboard,
  'layout-dashboard': LayoutDashboard,
  'list-checks': ListChecks,
  'message-circle': MessageCircle,
  'package-plus': PackagePlus,
  'package-search': PackageSearch,
  'panel-top': PanelTop,
  'receipt-text': ReceiptText,
  'repeat-2': Repeat2,
  route: Route,
  satellite: Satellite,
  send: Send,
  'shield-check': ShieldCheck,
  'shopping-cart': ShoppingCart,
  tags: Tags,
  'trending-up': TrendingUp,
  truck: Truck,
  'triangle-alert': TriangleAlert,
  users: Users,
  warehouse: Warehouse,
  wrench: Wrench,
}

export function getSidebarIcon(icon: string) {
  return sidebarIconMap[icon] || LayoutDashboard
}
