export const ROUTES = {
  root: '/',
  login: '/login',
  dashboard: '/dashboard',
  cases: '/cases',
  caseNew: '/cases/new',
  caseAssign: (caseId = ':caseId') => `/cases/${caseId}/assign`,
  caseDetail: (caseId = ':caseId') => `/cases/${caseId}`,
  caseEscalate: (caseId = ':caseId') => `/cases/${caseId}/escalate`,
  caseClose: (caseId = ':caseId') => `/cases/${caseId}/close`,
  schedule: '/schedule',
  bays: '/bays',
  trucks: '/trucks',
  truckNew: '/trucks/new',
  truckDetail: (truckId = ':truckId') => `/trucks/${truckId}`,
  diagnosticsRoot: '/diagnostics',
  diagnostics: (caseId = ':caseId') => `/diagnostics/${caseId}`,
  repairSolutions: (caseId = ':caseId') => `/repair-solutions/${caseId}`,
  assignments: '/assignments',
  mechanics: '/mechanics',
  mechanicSpecialties: '/mechanics/specialties',
  mechanicDetail: (mechanicId = ':mechanicId') => `/mechanics/${mechanicId}`,
  drivers: '/drivers',
  driverNew: '/drivers/new',
  driverDetail: (driverId = ':driverId') => `/drivers/${driverId}`,
  warehouse: '/warehouse',
  warehouseLocations: '/warehouse/locations',
  warehouseManagers: '/warehouse/managers',
  inventoryReport: '/warehouse/report',
  warehouseStock: '/warehouse/stock',
  purchaseOrders: '/purchase-orders',
  purchaseOrderNew: '/purchase-orders/new',
  purchaseOrderDetail: (purchaseOrderId = ':purchaseOrderId') => `/purchase-orders/${purchaseOrderId}`,
  purchaseInvoices: '/purchase-invoices',
  purchaseInvoiceNew: '/purchase-invoices/new',
  purchaseInvoiceDetail: (invoiceId = ':invoiceId') => `/purchase-invoices/${invoiceId}`,
  suppliers: '/suppliers',
  supplierNew: '/suppliers/new',
  supplierDetail: (supplierId = ':supplierId') => `/suppliers/${supplierId}`,
  quotes: '/quotes',
  quoteDetail: (quoteId = ':quoteId') => `/quotes/${quoteId}`,
  labor: '/labor',
  approvals: '/approvals',
  checklists: '/checklists',
  customers: '/customers',
  customerDetail: (customerId = ':customerId') => `/customers/${customerId}`,
  communications: '/communications',
  notifications: '/notifications',
  freightRequests: '/freight/requests',
  freightRequestNew: '/freight/requests/new',
  freightRequestDetail: (requestId = ':requestId') => `/freight/requests/${requestId}`,
  freightClientPortal: '/freight/client-portal',
  freightClientPortalRequests: '/freight/client-portal/requests',
  freightClientPortalHistory: '/freight/client-portal/history',
  freightClientPortalTracking: (trackingNumber = ':trackingNumber') => `/freight/client-portal/tracking/${trackingNumber}`,
  clientFreightRequest: '/portal/freight/request',
  clientFreightRequests: '/portal/freight/requests',
  clientFreightHistory: '/portal/freight/history',
  clientFreightTracking: (trackingNumber = ':trackingNumber') => `/portal/freight/tracking/${trackingNumber}`,
  freightQuotes: '/freight/quotes',
  freightQuoteDetail: (quoteId = ':quoteId') => `/freight/quotes/${quoteId}`,
  freightAssignments: '/freight/assignments',
  freightInvoices: '/freight/invoices',
  freightInvoiceNew: '/freight/invoices/new',
  freightInvoiceDetail: (invoiceId = ':invoiceId') => `/freight/invoices/${invoiceId}`,
  driverTripSheets: '/freight/driver-trip-sheets',
  tirePerformance: '/tire-performance',
  tirePerformanceIntake: '/tire-performance/intake',
  tirePerformanceInstall: '/tire-performance/install',
  tirePerformanceRemove: '/tire-performance/remove',
  tirePerformanceComparison: '/tire-performance/comparison',
  fleet: '/fleet',
  fleetTrucks: '/fleet/trucks',
  fleetTruckDetail: (truckId = ':truckId') => `/fleet/trucks/${truckId}`,
  fleetAvailability: '/fleet/availability',
  fleetHealthScore: '/fleet/health-score',
  preventiveMaintenance: '/preventive-maintenance',
  preventiveMaintenanceNew: '/preventive-maintenance/new',
  preventiveMaintenanceDetail: (planId = ':planId') => `/preventive-maintenance/${planId}`,
  truckCosts: '/truck-costs',
  truckCostDetail: (truckId = ':truckId') => `/truck-costs/${truckId}`,
  fuel: '/fuel',
  fuelNew: '/fuel/new',
  fuelReport: '/fuel/report',
  truckDocuments: '/truck-documents',
  truckDocumentDetail: (documentId = ':documentId') => `/truck-documents/${documentId}`,
  tripChecklists: '/trip-checklists',
  tripChecklistDeparture: '/trip-checklists/departure',
  tripChecklistArrival: '/trip-checklists/arrival',
  freightProfitability: '/freight-profitability',
  incidents: '/incidents',
  incidentsNew: '/incidents/new',
  incidentDetail: (incidentId = ':incidentId') => `/incidents/${incidentId}`,
  telematics: '/telematics',
  permissions: '/permissions',
  shortcutSettings: '/settings/shortcuts',
  parts: '/parts',
  partDetail: (partId = ':partId') => `/parts/${partId}`,
  reports: '/reports',
  driverPerformanceReport: '/reports/driver-performance',
}
